feat: basedir option added to configuration for generate command
nestjs/nest-cli pull request #2087
Opened 2023-05-17 22:20 UTC by yigitkurtcu

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

Issue Number: [#1849](https://github.com/nestjs/nest-cli/issues/1849)

## What is the new behavior?
Added a new option "baseDir". With this new option, new files related to this directory will be created and imported to the app module.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No

2023-05-17 22:22 UTC, yigitkurtcu commented
Pull request for Schemestore: https://github.com/SchemaStore/schemastore/pull/2967

2023-05-18 06:50 UTC, kamilmysliwiec commented on actions/generate.action.ts
> +    sourceRoot += `\/${configuration.generateOptions?.baseDir}`
we should use `path.join()` here

2023-05-18 10:23 UTC, yigitkurtcu commented on actions/generate.action.ts
> +    sourceRoot += `\/${configuration.generateOptions?.baseDir}`
Fixed

2023-05-19 10:32 UTC, yigitkurtcu commented
> Pull request for Schemestore: [SchemaStore/schemastore#2967](https://github.com/SchemaStore/schemastore/pull/2967)

By the way this pr has already been merged. @kamilmysliwiec

2023-07-18 02:07 UTC, micalevisk requested changes
please revert the changes made on `package-lock.json`. I don't think you meant to change that

hint: use `npm ci` instead of `npm install` otherwise may you'll end up touching that file :)

2023-07-18 02:10 UTC, micalevisk commented
also @yigitkurtcu woud you like to update the docs site as well? :eyes:

2023-11-23 10:08 UTC, Clovel commented
Any news on this ? It would indeed be a useful feature for the NestJS CLI !

2023-11-23 11:37 UTC, yigitkurtcu commented
I will update this.

2023-12-04 19:18 UTC, closed without merging

2025-06-23 09:55 UTC, hi-reeve commented
why is this closed? any alternative?