feat(new): check for installed package managers
nestjs/nest-cli pull request #2495
Opened 2024-02-03 17:48 UTC by onurravli

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[X] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Currently, the CLI tool asks for all package managers (npm, yarn, and pnpm) even if they aren't installed.

## What is the new behavior?

Now, CLI checks for installed package managers and then asks for those that are installed, not for the ones that are not installed.

## Does this PR introduce a breaking change?
```
[ ] Yes
[X] No
```

2024-02-04 09:00 UTC, onurravli commented
Hey @kamilmysliwiec, can you check this out?

2024-02-04 15:22 UTC, micalevisk commented on actions/new.action.ts
> +  } catch (error) {
```suggestion
  } catch {
```

2024-02-04 15:33 UTC, onurravli commented on actions/new.action.ts
> +  } catch (error) {
56493f6d.

2024-02-04 15:41 UTC, micalevisk approved these changes

2024-02-04 20:26 UTC, Tony133 requested changes

2024-02-04 20:44 UTC, onurravli commented on actions/new.action.ts
> +    installedPackageManagers.push(PackageManager.PNPM);
c517e57.

2024-02-04 21:55 UTC, Tony133 approved these changes

2024-02-05 07:34 UTC, kamilmysliwiec commented
Not sure how I feel about this change. Isn't this confusing that some options just won't show up for certain people? Like one might be aware that yarn is a thing but doesn't have it installed on let's say their machine at work. Then they generate a NestJS app and they only see NPM showing up which will make them think using yarn was never an option (simply because it's hidden).

Shouldn't we just leave this decision to the developer since the developer should be aware of what tool they have installed (and even if they don't they can always terminate the command, install it, and start over) and want to use for their projects?

2024-02-05 07:46 UTC, Tony133 commented
Yes, this is a bit of a "divisive" change, to one 50 percent it can be helpful while the other 50 percent can be confusing 😄

2024-02-05 07:51 UTC, onurravli commented
> Not sure how I feel about this change. Isn't this confusing that some options just won't show up for certain people? Like one might be aware that yarn is a thing but doesn't have it installed on let's say their machine at work. Then they generate a NestJS app and they only see NPM showing up which will make them think using yarn was never an option (simply because it's hidden).
> 
> Shouldn't we just leave this decision to the developer since the developer should be aware of what tool they have installed (and even if they don't they can always terminate the command, install it, and start over) and want to use for their projects?

I made this change after I realize there is an error when you continue with yarn even yarn is not installed, as below.

![image](https://github.com/nestjs/nest-cli/assets/47084109/6444277d-c6cd-4ee8-abf3-9a73e7c1ebbd)

If it's not a good idea to hide package managers, it might be a better idea to warn the user if, for example, yarn is not installed, but to build the project (without installing packages).

2024-02-05 07:53 UTC, kamilmysliwiec commented
Even if the installation fails, everything else should be properly generated and you should be good to go as long as you manually install dependencies

2024-02-05 07:54 UTC, onurravli commented
Yes, I mean the error is not clear. In my firs use of nest-cli, I thought project wasn't built.

2024-02-05 08:00 UTC, kamilmysliwiec commented
So maybe instead of hiding package managers we should rather improve our error messages; let users know that even if the installation failed they're generally (almost) all set

2024-02-05 08:09 UTC, kamilmysliwiec commented
Feel free to continue in this PR

2024-07-02 07:06 UTC, closed without merging